version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: testtest123
    command: server /data
  adminio-api:
    image: rzrbld/adminio-api:0.2
    environment:
      MINIO_ACCESS: test
      MINIO_SECRET: testtest123
    depends_on:
      - minio
    ports:
      - "8080:8080"
  adminio-ui:
    image: rzrbld/adminio-ui-demo:0.2
    ports:
      - "80:80"
